api_version = "2025-07"

[[extensions]]
uid = "587c72a4-6849-c6c2-4158-af8ec1e3669be06591a1"
type = "ui_extension"
name = "eSIM Order Status"
handle = "esim-order-status"

  [[extensions.targeting]]
  module = "./src/OrderStatusBlock.tsx"
  target = "customer-account.order-status.cart-line-item.render-after"

  [[extensions.targeting]]
  module = "./src/OrderActionMenuItem.tsx"
  target = "customer-account.order.action.menu-item.render"

  [[extensions.targeting]]
  module = "./src/OrderBlock.tsx"
  target = "customer-account.order.action.render"

  [[extensions.metafields]]
  namespace = "esim"
  key = "delivery_tokens"
