/**
 * ISO 3166-1 alpha-2 country code lookup + FiRoam display-name mapping.
 * Used by bulk product creation to resolve country names to codes.
 */

export interface CountryInfo {
  code: string; // ISO alpha-2
  name: string; // Display name
  slug: string; // URL-friendly handle
}

/** Full ISO 3166-1 alpha-2 country list. */
const COUNTRIES: CountryInfo[] = [
  { code: 'AF', name: 'Afghanistan', slug: 'afghanistan' },
  { code: 'AL', name: 'Albania', slug: 'albania' },
  { code: 'DZ', name: 'Algeria', slug: 'algeria' },
  { code: 'AD', name: 'Andorra', slug: 'andorra' },
  { code: 'AO', name: 'Angola', slug: 'angola' },
  { code: 'AI', name: 'Anguilla', slug: 'anguilla' },
  { code: 'AG', name: 'Antigua and Barbuda', slug: 'antigua-and-barbuda' },
  { code: 'AR', name: 'Argentina', slug: 'argentina' },
  { code: 'AM', name: 'Armenia', slug: 'armenia' },
  { code: 'AU', name: 'Australia', slug: 'australia' },
  { code: 'AT', name: 'Austria', slug: 'austria' },
  { code: 'AZ', name: 'Azerbaijan', slug: 'azerbaijan' },
  { code: 'BS', name: 'Bahamas', slug: 'bahamas' },
  { code: 'BH', name: 'Bahrain', slug: 'bahrain' },
  { code: 'BD', name: 'Bangladesh', slug: 'bangladesh' },
  { code: 'BB', name: 'Barbados', slug: 'barbados' },
  { code: 'BY', name: 'Belarus', slug: 'belarus' },
  { code: 'BE', name: 'Belgium', slug: 'belgium' },
  { code: 'BZ', name: 'Belize', slug: 'belize' },
  { code: 'BJ', name: 'Benin', slug: 'benin' },
  { code: 'BM', name: 'Bermuda', slug: 'bermuda' },
  { code: 'BT', name: 'Bhutan', slug: 'bhutan' },
  { code: 'BO', name: 'Bolivia', slug: 'bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina', slug: 'bosnia-and-herzegovina' },
  { code: 'BW', name: 'Botswana', slug: 'botswana' },
  { code: 'BR', name: 'Brazil', slug: 'brazil' },
  { code: 'BN', name: 'Brunei', slug: 'brunei' },
  { code: 'BG', name: 'Bulgaria', slug: 'bulgaria' },
  { code: 'BF', name: 'Burkina Faso', slug: 'burkina-faso' },
  { code: 'BI', name: 'Burundi', slug: 'burundi' },
  { code: 'KH', name: 'Cambodia', slug: 'cambodia' },
  { code: 'CM', name: 'Cameroon', slug: 'cameroon' },
  { code: 'CA', name: 'Canada', slug: 'canada' },
  { code: 'CV', name: 'Cape Verde', slug: 'cape-verde' },
  { code: 'KY', name: 'Cayman Islands', slug: 'cayman-islands' },
  { code: 'CF', name: 'Central African Republic', slug: 'central-african-republic' },
  { code: 'TD', name: 'Chad', slug: 'chad' },
  { code: 'CL', name: 'Chile', slug: 'chile' },
  { code: 'CN', name: 'China', slug: 'china' },
  { code: 'CO', name: 'Colombia', slug: 'colombia' },
  { code: 'KM', name: 'Comoros', slug: 'comoros' },
  { code: 'CG', name: 'Republic of the Congo', slug: 'republic-of-the-congo' },
  { code: 'CD', name: 'DR Congo', slug: 'dr-congo' },
  { code: 'CR', name: 'Costa Rica', slug: 'costa-rica' },
  { code: 'CI', name: "Cote d'Ivoire", slug: 'cote-divoire' },
  { code: 'HR', name: 'Croatia', slug: 'croatia' },
  { code: 'CU', name: 'Cuba', slug: 'cuba' },
  { code: 'CW', name: 'Curacao', slug: 'curacao' },
  { code: 'CY', name: 'Cyprus', slug: 'cyprus' },
  { code: 'CZ', name: 'Czech Republic', slug: 'czech-republic' },
  { code: 'DK', name: 'Denmark', slug: 'denmark' },
  { code: 'DJ', name: 'Djibouti', slug: 'djibouti' },
  { code: 'DM', name: 'Dominica', slug: 'dominica' },
  { code: 'DO', name: 'Dominican Republic', slug: 'dominican-republic' },
  { code: 'EC', name: 'Ecuador', slug: 'ecuador' },
  { code: 'EG', name: 'Egypt', slug: 'egypt' },
  { code: 'SV', name: 'El Salvador', slug: 'el-salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', slug: 'equatorial-guinea' },
  { code: 'ER', name: 'Eritrea', slug: 'eritrea' },
  { code: 'EE', name: 'Estonia', slug: 'estonia' },
  { code: 'SZ', name: 'Eswatini', slug: 'eswatini' },
  { code: 'ET', name: 'Ethiopia', slug: 'ethiopia' },
  { code: 'FJ', name: 'Fiji', slug: 'fiji' },
  { code: 'FI', name: 'Finland', slug: 'finland' },
  { code: 'FR', name: 'France', slug: 'france' },
  { code: 'GF', name: 'French Guiana', slug: 'french-guiana' },
  { code: 'PF', name: 'French Polynesia', slug: 'french-polynesia' },
  { code: 'GA', name: 'Gabon', slug: 'gabon' },
  { code: 'GM', name: 'Gambia', slug: 'gambia' },
  { code: 'GE', name: 'Georgia', slug: 'georgia' },
  { code: 'DE', name: 'Germany', slug: 'germany' },
  { code: 'GH', name: 'Ghana', slug: 'ghana' },
  { code: 'GI', name: 'Gibraltar', slug: 'gibraltar' },
  { code: 'GR', name: 'Greece', slug: 'greece' },
  { code: 'GL', name: 'Greenland', slug: 'greenland' },
  { code: 'GD', name: 'Grenada', slug: 'grenada' },
  { code: 'GP', name: 'Guadeloupe', slug: 'guadeloupe' },
  { code: 'GU', name: 'Guam', slug: 'guam' },
  { code: 'GT', name: 'Guatemala', slug: 'guatemala' },
  { code: 'GN', name: 'Guinea', slug: 'guinea' },
  { code: 'GW', name: 'Guinea-Bissau', slug: 'guinea-bissau' },
  { code: 'GY', name: 'Guyana', slug: 'guyana' },
  { code: 'HT', name: 'Haiti', slug: 'haiti' },
  { code: 'HN', name: 'Honduras', slug: 'honduras' },
  { code: 'HK', name: 'Hong Kong', slug: 'hong-kong' },
  { code: 'HU', name: 'Hungary', slug: 'hungary' },
  { code: 'IS', name: 'Iceland', slug: 'iceland' },
  { code: 'IN', name: 'India', slug: 'india' },
  { code: 'ID', name: 'Indonesia', slug: 'indonesia' },
  { code: 'IR', name: 'Iran', slug: 'iran' },
  { code: 'IQ', name: 'Iraq', slug: 'iraq' },
  { code: 'IE', name: 'Ireland', slug: 'ireland' },
  { code: 'IL', name: 'Israel', slug: 'israel' },
  { code: 'IT', name: 'Italy', slug: 'italy' },
  { code: 'JM', name: 'Jamaica', slug: 'jamaica' },
  { code: 'JP', name: 'Japan', slug: 'japan' },
  { code: 'JO', name: 'Jordan', slug: 'jordan' },
  { code: 'KZ', name: 'Kazakhstan', slug: 'kazakhstan' },
  { code: 'KE', name: 'Kenya', slug: 'kenya' },
  { code: 'KR', name: 'South Korea', slug: 'south-korea' },
  { code: 'KW', name: 'Kuwait', slug: 'kuwait' },
  { code: 'KG', name: 'Kyrgyzstan', slug: 'kyrgyzstan' },
  { code: 'LA', name: 'Laos', slug: 'laos' },
  { code: 'LV', name: 'Latvia', slug: 'latvia' },
  { code: 'LB', name: 'Lebanon', slug: 'lebanon' },
  { code: 'LS', name: 'Lesotho', slug: 'lesotho' },
  { code: 'LR', name: 'Liberia', slug: 'liberia' },
  { code: 'LY', name: 'Libya', slug: 'libya' },
  { code: 'LI', name: 'Liechtenstein', slug: 'liechtenstein' },
  { code: 'LT', name: 'Lithuania', slug: 'lithuania' },
  { code: 'LU', name: 'Luxembourg', slug: 'luxembourg' },
  { code: 'MO', name: 'Macau', slug: 'macau' },
  { code: 'MK', name: 'North Macedonia', slug: 'north-macedonia' },
  { code: 'MG', name: 'Madagascar', slug: 'madagascar' },
  { code: 'MW', name: 'Malawi', slug: 'malawi' },
  { code: 'MY', name: 'Malaysia', slug: 'malaysia' },
  { code: 'MV', name: 'Maldives', slug: 'maldives' },
  { code: 'ML', name: 'Mali', slug: 'mali' },
  { code: 'MT', name: 'Malta', slug: 'malta' },
  { code: 'MQ', name: 'Martinique', slug: 'martinique' },
  { code: 'MR', name: 'Mauritania', slug: 'mauritania' },
  { code: 'MU', name: 'Mauritius', slug: 'mauritius' },
  { code: 'MX', name: 'Mexico', slug: 'mexico' },
  { code: 'MD', name: 'Moldova', slug: 'moldova' },
  { code: 'MC', name: 'Monaco', slug: 'monaco' },
  { code: 'MN', name: 'Mongolia', slug: 'mongolia' },
  { code: 'ME', name: 'Montenegro', slug: 'montenegro' },
  { code: 'MS', name: 'Montserrat', slug: 'montserrat' },
  { code: 'MA', name: 'Morocco', slug: 'morocco' },
  { code: 'MZ', name: 'Mozambique', slug: 'mozambique' },
  { code: 'MM', name: 'Myanmar', slug: 'myanmar' },
  { code: 'NA', name: 'Namibia', slug: 'namibia' },
  { code: 'NP', name: 'Nepal', slug: 'nepal' },
  { code: 'NL', name: 'Netherlands', slug: 'netherlands' },
  { code: 'NC', name: 'New Caledonia', slug: 'new-caledonia' },
  { code: 'NZ', name: 'New Zealand', slug: 'new-zealand' },
  { code: 'NI', name: 'Nicaragua', slug: 'nicaragua' },
  { code: 'NE', name: 'Niger', slug: 'niger' },
  { code: 'NG', name: 'Nigeria', slug: 'nigeria' },
  { code: 'NO', name: 'Norway', slug: 'norway' },
  { code: 'OM', name: 'Oman', slug: 'oman' },
  { code: 'PK', name: 'Pakistan', slug: 'pakistan' },
  { code: 'PA', name: 'Panama', slug: 'panama' },
  { code: 'PG', name: 'Papua New Guinea', slug: 'papua-new-guinea' },
  { code: 'PY', name: 'Paraguay', slug: 'paraguay' },
  { code: 'PE', name: 'Peru', slug: 'peru' },
  { code: 'PH', name: 'Philippines', slug: 'philippines' },
  { code: 'PL', name: 'Poland', slug: 'poland' },
  { code: 'PT', name: 'Portugal', slug: 'portugal' },
  { code: 'PR', name: 'Puerto Rico', slug: 'puerto-rico' },
  { code: 'QA', name: 'Qatar', slug: 'qatar' },
  { code: 'RE', name: 'Reunion', slug: 'reunion' },
  { code: 'RO', name: 'Romania', slug: 'romania' },
  { code: 'RU', name: 'Russia', slug: 'russia' },
  { code: 'RW', name: 'Rwanda', slug: 'rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis', slug: 'saint-kitts-and-nevis' },
  { code: 'LC', name: 'Saint Lucia', slug: 'saint-lucia' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    slug: 'saint-vincent-and-the-grenadines',
  },
  { code: 'WS', name: 'Samoa', slug: 'samoa' },
  { code: 'SM', name: 'San Marino', slug: 'san-marino' },
  { code: 'SA', name: 'Saudi Arabia', slug: 'saudi-arabia' },
  { code: 'SN', name: 'Senegal', slug: 'senegal' },
  { code: 'RS', name: 'Serbia', slug: 'serbia' },
  { code: 'SC', name: 'Seychelles', slug: 'seychelles' },
  { code: 'SL', name: 'Sierra Leone', slug: 'sierra-leone' },
  { code: 'SG', name: 'Singapore', slug: 'singapore' },
  { code: 'SK', name: 'Slovakia', slug: 'slovakia' },
  { code: 'SI', name: 'Slovenia', slug: 'slovenia' },
  { code: 'SB', name: 'Solomon Islands', slug: 'solomon-islands' },
  { code: 'SO', name: 'Somalia', slug: 'somalia' },
  { code: 'ZA', name: 'South Africa', slug: 'south-africa' },
  { code: 'SS', name: 'South Sudan', slug: 'south-sudan' },
  { code: 'ES', name: 'Spain', slug: 'spain' },
  { code: 'LK', name: 'Sri Lanka', slug: 'sri-lanka' },
  { code: 'SD', name: 'Sudan', slug: 'sudan' },
  { code: 'SR', name: 'Suriname', slug: 'suriname' },
  { code: 'SE', name: 'Sweden', slug: 'sweden' },
  { code: 'CH', name: 'Switzerland', slug: 'switzerland' },
  { code: 'TW', name: 'Taiwan', slug: 'taiwan' },
  { code: 'TJ', name: 'Tajikistan', slug: 'tajikistan' },
  { code: 'TZ', name: 'Tanzania', slug: 'tanzania' },
  { code: 'TH', name: 'Thailand', slug: 'thailand' },
  { code: 'TL', name: 'Timor-Leste', slug: 'timor-leste' },
  { code: 'TG', name: 'Togo', slug: 'togo' },
  { code: 'TO', name: 'Tonga', slug: 'tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago' },
  { code: 'TN', name: 'Tunisia', slug: 'tunisia' },
  { code: 'TR', name: 'Turkey', slug: 'turkey' },
  { code: 'TC', name: 'Turks and Caicos Islands', slug: 'turks-and-caicos-islands' },
  { code: 'UG', name: 'Uganda', slug: 'uganda' },
  { code: 'UA', name: 'Ukraine', slug: 'ukraine' },
  { code: 'AE', name: 'United Arab Emirates', slug: 'united-arab-emirates' },
  { code: 'GB', name: 'United Kingdom', slug: 'united-kingdom' },
  { code: 'US', name: 'United States', slug: 'united-states' },
  { code: 'UY', name: 'Uruguay', slug: 'uruguay' },
  { code: 'UZ', name: 'Uzbekistan', slug: 'uzbekistan' },
  { code: 'VU', name: 'Vanuatu', slug: 'vanuatu' },
  { code: 'VA', name: 'Vatican City', slug: 'vatican-city' },
  { code: 'VE', name: 'Venezuela', slug: 'venezuela' },
  { code: 'VN', name: 'Vietnam', slug: 'vietnam' },
  { code: 'YE', name: 'Yemen', slug: 'yemen' },
  { code: 'ZM', name: 'Zambia', slug: 'zambia' },
  { code: 'ZW', name: 'Zimbabwe', slug: 'zimbabwe' },
  { code: 'FO', name: 'Faroe Islands', slug: 'faroe-islands' },
  { code: 'BQ', name: 'Bonaire', slug: 'bonaire' },
];

const byCode = new Map<string, CountryInfo>();
for (const c of COUNTRIES) {
  byCode.set(c.code, c);
}

/** FiRoam display names → ISO code. Only single-country names; regional bundles are excluded. */
const FIROAM_NAME_TO_CODE: Record<string, string> = {
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Anguilla: 'AI',
  'Antigua & Barbuda': 'AG',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Bolivia: 'BO',
  'Bosnia &  Herzegovina': 'BA',
  Brazil: 'BR',
  Brunei: 'BN',
  Bulgaria: 'BG',
  Cambodia: 'KH',
  Canada: 'CA',
  'Cayman Islands': 'KY',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  'China.HongKong': 'HK',
  'China.Macau': 'MO',
  'China.Taiwan': 'TW',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  DRC: 'CD',
  Denmark: 'DK',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  Estonia: 'EE',
  'Faroe Islands': 'FO',
  Fiji: 'FJ',
  Finland: 'FI',
  France: 'FR',
  'French Guiana': 'GF',
  Gabon: 'GA',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Grenada: 'GD',
  Guatemala: 'GT',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Korea: 'KR',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Latvia: 'LV',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Macedonia: 'MK',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Malta: 'MT',
  Mauritius: 'MU',
  Mexico: 'MX',
  Moldova: 'MD',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Montserrat: 'MS',
  Morocco: 'MA',
  Nepal: 'NP',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Republic of the Congo': 'CG',
  Reunion: 'RE',
  Romania: 'RO',
  Russia: 'RU',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  'St. Kitts & Nevis': 'KN',
  'St. Lucia': 'LC',
  'St. Vincent & the Grenadines': 'VC',
  Sweden: 'SE',
  Switzerland: 'CH',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  Tonga: 'TO',
  Tunisia: 'TN',
  Turkey: 'TR',
  'Turks & Caicos Islands': 'TC',
  UAE: 'AE',
  USA: 'US',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Kingdom': 'GB',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  'Vatican City': 'VA',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Zambia: 'ZM',
};

export function getCountryByCode(code: string): CountryInfo | undefined {
  return byCode.get(code.toUpperCase());
}

/** Resolve a FiRoam display name to an ISO code. Returns undefined for regional bundles. */
export function firoamNameToCode(name: string): string | undefined {
  return FIROAM_NAME_TO_CODE[name];
}
