/**
 * ISO 3166-1 alpha-2 country code lookup + FiRoam display-name mapping.
 * Used by bulk product creation to resolve country names to codes.
 */

export interface CountryInfo {
  code: string; // ISO alpha-2
  name: string; // Display name
  slug: string; // URL-friendly handle
  region: string; // Geographic region
}

/** Full ISO 3166-1 alpha-2 country list. */
const COUNTRIES: CountryInfo[] = [
  { code: 'AF', name: 'Afghanistan', slug: 'afghanistan', region: 'Asia' },
  { code: 'AL', name: 'Albania', slug: 'albania', region: 'Europe' },
  { code: 'DZ', name: 'Algeria', slug: 'algeria', region: 'Africa' },
  { code: 'AD', name: 'Andorra', slug: 'andorra', region: 'Europe' },
  { code: 'AO', name: 'Angola', slug: 'angola', region: 'Africa' },
  { code: 'AI', name: 'Anguilla', slug: 'anguilla', region: 'Caribbean' },
  { code: 'AG', name: 'Antigua and Barbuda', slug: 'antigua-and-barbuda', region: 'Caribbean' },
  { code: 'AR', name: 'Argentina', slug: 'argentina', region: 'South America' },
  { code: 'AM', name: 'Armenia', slug: 'armenia', region: 'Asia' },
  { code: 'AU', name: 'Australia', slug: 'australia', region: 'Oceania' },
  { code: 'AT', name: 'Austria', slug: 'austria', region: 'Europe' },
  { code: 'AZ', name: 'Azerbaijan', slug: 'azerbaijan', region: 'Asia' },
  { code: 'BS', name: 'Bahamas', slug: 'bahamas', region: 'Caribbean' },
  { code: 'BH', name: 'Bahrain', slug: 'bahrain', region: 'Middle East' },
  { code: 'BD', name: 'Bangladesh', slug: 'bangladesh', region: 'Asia' },
  { code: 'BB', name: 'Barbados', slug: 'barbados', region: 'Caribbean' },
  { code: 'BY', name: 'Belarus', slug: 'belarus', region: 'Europe' },
  { code: 'BE', name: 'Belgium', slug: 'belgium', region: 'Europe' },
  { code: 'BZ', name: 'Belize', slug: 'belize', region: 'Central America' },
  { code: 'BJ', name: 'Benin', slug: 'benin', region: 'Africa' },
  { code: 'BM', name: 'Bermuda', slug: 'bermuda', region: 'Caribbean' },
  { code: 'BT', name: 'Bhutan', slug: 'bhutan', region: 'Asia' },
  { code: 'BO', name: 'Bolivia', slug: 'bolivia', region: 'South America' },
  { code: 'BA', name: 'Bosnia and Herzegovina', slug: 'bosnia-and-herzegovina', region: 'Europe' },
  { code: 'BW', name: 'Botswana', slug: 'botswana', region: 'Africa' },
  { code: 'BR', name: 'Brazil', slug: 'brazil', region: 'South America' },
  { code: 'BN', name: 'Brunei', slug: 'brunei', region: 'Asia' },
  { code: 'BG', name: 'Bulgaria', slug: 'bulgaria', region: 'Europe' },
  { code: 'BF', name: 'Burkina Faso', slug: 'burkina-faso', region: 'Africa' },
  { code: 'BI', name: 'Burundi', slug: 'burundi', region: 'Africa' },
  { code: 'KH', name: 'Cambodia', slug: 'cambodia', region: 'Asia' },
  { code: 'CM', name: 'Cameroon', slug: 'cameroon', region: 'Africa' },
  { code: 'CA', name: 'Canada', slug: 'canada', region: 'North America' },
  { code: 'CV', name: 'Cape Verde', slug: 'cape-verde', region: 'Africa' },
  { code: 'KY', name: 'Cayman Islands', slug: 'cayman-islands', region: 'Caribbean' },
  {
    code: 'CF',
    name: 'Central African Republic',
    slug: 'central-african-republic',
    region: 'Africa',
  },
  { code: 'TD', name: 'Chad', slug: 'chad', region: 'Africa' },
  { code: 'CL', name: 'Chile', slug: 'chile', region: 'South America' },
  { code: 'CN', name: 'China', slug: 'china', region: 'Asia' },
  { code: 'CO', name: 'Colombia', slug: 'colombia', region: 'South America' },
  { code: 'KM', name: 'Comoros', slug: 'comoros', region: 'Africa' },
  { code: 'CG', name: 'Republic of the Congo', slug: 'republic-of-the-congo', region: 'Africa' },
  { code: 'CD', name: 'DR Congo', slug: 'dr-congo', region: 'Africa' },
  { code: 'CR', name: 'Costa Rica', slug: 'costa-rica', region: 'Central America' },
  { code: 'CI', name: "Cote d'Ivoire", slug: 'cote-divoire', region: 'Africa' },
  { code: 'HR', name: 'Croatia', slug: 'croatia', region: 'Europe' },
  { code: 'CU', name: 'Cuba', slug: 'cuba', region: 'Caribbean' },
  { code: 'CW', name: 'Curacao', slug: 'curacao', region: 'Caribbean' },
  { code: 'CY', name: 'Cyprus', slug: 'cyprus', region: 'Middle East' },
  { code: 'CZ', name: 'Czech Republic', slug: 'czech-republic', region: 'Europe' },
  { code: 'DK', name: 'Denmark', slug: 'denmark', region: 'Europe' },
  { code: 'DJ', name: 'Djibouti', slug: 'djibouti', region: 'Africa' },
  { code: 'DM', name: 'Dominica', slug: 'dominica', region: 'Caribbean' },
  { code: 'DO', name: 'Dominican Republic', slug: 'dominican-republic', region: 'Caribbean' },
  { code: 'EC', name: 'Ecuador', slug: 'ecuador', region: 'South America' },
  { code: 'EG', name: 'Egypt', slug: 'egypt', region: 'Africa' },
  { code: 'SV', name: 'El Salvador', slug: 'el-salvador', region: 'Central America' },
  { code: 'GQ', name: 'Equatorial Guinea', slug: 'equatorial-guinea', region: 'Africa' },
  { code: 'ER', name: 'Eritrea', slug: 'eritrea', region: 'Africa' },
  { code: 'EE', name: 'Estonia', slug: 'estonia', region: 'Europe' },
  { code: 'SZ', name: 'Eswatini', slug: 'eswatini', region: 'Africa' },
  { code: 'ET', name: 'Ethiopia', slug: 'ethiopia', region: 'Africa' },
  { code: 'FJ', name: 'Fiji', slug: 'fiji', region: 'Oceania' },
  { code: 'FI', name: 'Finland', slug: 'finland', region: 'Europe' },
  { code: 'FR', name: 'France', slug: 'france', region: 'Europe' },
  { code: 'GF', name: 'French Guiana', slug: 'french-guiana', region: 'South America' },
  { code: 'PF', name: 'French Polynesia', slug: 'french-polynesia', region: 'Oceania' },
  { code: 'GA', name: 'Gabon', slug: 'gabon', region: 'Africa' },
  { code: 'GM', name: 'Gambia', slug: 'gambia', region: 'Africa' },
  { code: 'GE', name: 'Georgia', slug: 'georgia', region: 'Asia' },
  { code: 'DE', name: 'Germany', slug: 'germany', region: 'Europe' },
  { code: 'GH', name: 'Ghana', slug: 'ghana', region: 'Africa' },
  { code: 'GI', name: 'Gibraltar', slug: 'gibraltar', region: 'Europe' },
  { code: 'GR', name: 'Greece', slug: 'greece', region: 'Europe' },
  { code: 'GL', name: 'Greenland', slug: 'greenland', region: 'North America' },
  { code: 'GD', name: 'Grenada', slug: 'grenada', region: 'Caribbean' },
  { code: 'GP', name: 'Guadeloupe', slug: 'guadeloupe', region: 'Caribbean' },
  { code: 'GU', name: 'Guam', slug: 'guam', region: 'Oceania' },
  { code: 'GT', name: 'Guatemala', slug: 'guatemala', region: 'Central America' },
  { code: 'GN', name: 'Guinea', slug: 'guinea', region: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau', slug: 'guinea-bissau', region: 'Africa' },
  { code: 'GY', name: 'Guyana', slug: 'guyana', region: 'South America' },
  { code: 'HT', name: 'Haiti', slug: 'haiti', region: 'Caribbean' },
  { code: 'HN', name: 'Honduras', slug: 'honduras', region: 'Central America' },
  { code: 'HK', name: 'Hong Kong', slug: 'hong-kong', region: 'Asia' },
  { code: 'HU', name: 'Hungary', slug: 'hungary', region: 'Europe' },
  { code: 'IS', name: 'Iceland', slug: 'iceland', region: 'Europe' },
  { code: 'IN', name: 'India', slug: 'india', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', slug: 'indonesia', region: 'Asia' },
  { code: 'IR', name: 'Iran', slug: 'iran', region: 'Middle East' },
  { code: 'IQ', name: 'Iraq', slug: 'iraq', region: 'Middle East' },
  { code: 'IE', name: 'Ireland', slug: 'ireland', region: 'Europe' },
  { code: 'IL', name: 'Israel', slug: 'israel', region: 'Middle East' },
  { code: 'IT', name: 'Italy', slug: 'italy', region: 'Europe' },
  { code: 'JM', name: 'Jamaica', slug: 'jamaica', region: 'Caribbean' },
  { code: 'JP', name: 'Japan', slug: 'japan', region: 'Asia' },
  { code: 'JO', name: 'Jordan', slug: 'jordan', region: 'Middle East' },
  { code: 'KZ', name: 'Kazakhstan', slug: 'kazakhstan', region: 'Asia' },
  { code: 'KE', name: 'Kenya', slug: 'kenya', region: 'Africa' },
  { code: 'KR', name: 'South Korea', slug: 'south-korea', region: 'Asia' },
  { code: 'KW', name: 'Kuwait', slug: 'kuwait', region: 'Middle East' },
  { code: 'KG', name: 'Kyrgyzstan', slug: 'kyrgyzstan', region: 'Asia' },
  { code: 'LA', name: 'Laos', slug: 'laos', region: 'Asia' },
  { code: 'LV', name: 'Latvia', slug: 'latvia', region: 'Europe' },
  { code: 'LB', name: 'Lebanon', slug: 'lebanon', region: 'Middle East' },
  { code: 'LS', name: 'Lesotho', slug: 'lesotho', region: 'Africa' },
  { code: 'LR', name: 'Liberia', slug: 'liberia', region: 'Africa' },
  { code: 'LY', name: 'Libya', slug: 'libya', region: 'Africa' },
  { code: 'LI', name: 'Liechtenstein', slug: 'liechtenstein', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', slug: 'lithuania', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', slug: 'luxembourg', region: 'Europe' },
  { code: 'MO', name: 'Macau', slug: 'macau', region: 'Asia' },
  { code: 'MK', name: 'North Macedonia', slug: 'north-macedonia', region: 'Europe' },
  { code: 'MG', name: 'Madagascar', slug: 'madagascar', region: 'Africa' },
  { code: 'MW', name: 'Malawi', slug: 'malawi', region: 'Africa' },
  { code: 'MY', name: 'Malaysia', slug: 'malaysia', region: 'Asia' },
  { code: 'MV', name: 'Maldives', slug: 'maldives', region: 'Asia' },
  { code: 'ML', name: 'Mali', slug: 'mali', region: 'Africa' },
  { code: 'MT', name: 'Malta', slug: 'malta', region: 'Europe' },
  { code: 'MQ', name: 'Martinique', slug: 'martinique', region: 'Caribbean' },
  { code: 'MR', name: 'Mauritania', slug: 'mauritania', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', slug: 'mauritius', region: 'Africa' },
  { code: 'MX', name: 'Mexico', slug: 'mexico', region: 'North America' },
  { code: 'MD', name: 'Moldova', slug: 'moldova', region: 'Europe' },
  { code: 'MC', name: 'Monaco', slug: 'monaco', region: 'Europe' },
  { code: 'MN', name: 'Mongolia', slug: 'mongolia', region: 'Asia' },
  { code: 'ME', name: 'Montenegro', slug: 'montenegro', region: 'Europe' },
  { code: 'MS', name: 'Montserrat', slug: 'montserrat', region: 'Caribbean' },
  { code: 'MA', name: 'Morocco', slug: 'morocco', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', slug: 'mozambique', region: 'Africa' },
  { code: 'MM', name: 'Myanmar', slug: 'myanmar', region: 'Asia' },
  { code: 'NA', name: 'Namibia', slug: 'namibia', region: 'Africa' },
  { code: 'NP', name: 'Nepal', slug: 'nepal', region: 'Asia' },
  { code: 'NL', name: 'Netherlands', slug: 'netherlands', region: 'Europe' },
  { code: 'NC', name: 'New Caledonia', slug: 'new-caledonia', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', slug: 'new-zealand', region: 'Oceania' },
  { code: 'NI', name: 'Nicaragua', slug: 'nicaragua', region: 'Central America' },
  { code: 'NE', name: 'Niger', slug: 'niger', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', slug: 'nigeria', region: 'Africa' },
  { code: 'NO', name: 'Norway', slug: 'norway', region: 'Europe' },
  { code: 'OM', name: 'Oman', slug: 'oman', region: 'Middle East' },
  { code: 'PK', name: 'Pakistan', slug: 'pakistan', region: 'Asia' },
  { code: 'PA', name: 'Panama', slug: 'panama', region: 'Central America' },
  { code: 'PG', name: 'Papua New Guinea', slug: 'papua-new-guinea', region: 'Oceania' },
  { code: 'PY', name: 'Paraguay', slug: 'paraguay', region: 'South America' },
  { code: 'PE', name: 'Peru', slug: 'peru', region: 'South America' },
  { code: 'PH', name: 'Philippines', slug: 'philippines', region: 'Asia' },
  { code: 'PL', name: 'Poland', slug: 'poland', region: 'Europe' },
  { code: 'PT', name: 'Portugal', slug: 'portugal', region: 'Europe' },
  { code: 'PR', name: 'Puerto Rico', slug: 'puerto-rico', region: 'Caribbean' },
  { code: 'QA', name: 'Qatar', slug: 'qatar', region: 'Middle East' },
  { code: 'RE', name: 'Reunion', slug: 'reunion', region: 'Africa' },
  { code: 'RO', name: 'Romania', slug: 'romania', region: 'Europe' },
  { code: 'RU', name: 'Russia', slug: 'russia', region: 'Europe' },
  { code: 'RW', name: 'Rwanda', slug: 'rwanda', region: 'Africa' },
  { code: 'KN', name: 'Saint Kitts and Nevis', slug: 'saint-kitts-and-nevis', region: 'Caribbean' },
  { code: 'LC', name: 'Saint Lucia', slug: 'saint-lucia', region: 'Caribbean' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    slug: 'saint-vincent-and-the-grenadines',
    region: 'Caribbean',
  },
  { code: 'WS', name: 'Samoa', slug: 'samoa', region: 'Oceania' },
  { code: 'SM', name: 'San Marino', slug: 'san-marino', region: 'Europe' },
  { code: 'SA', name: 'Saudi Arabia', slug: 'saudi-arabia', region: 'Middle East' },
  { code: 'SN', name: 'Senegal', slug: 'senegal', region: 'Africa' },
  { code: 'RS', name: 'Serbia', slug: 'serbia', region: 'Europe' },
  { code: 'SC', name: 'Seychelles', slug: 'seychelles', region: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', slug: 'sierra-leone', region: 'Africa' },
  { code: 'SG', name: 'Singapore', slug: 'singapore', region: 'Asia' },
  { code: 'SK', name: 'Slovakia', slug: 'slovakia', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', slug: 'slovenia', region: 'Europe' },
  { code: 'SB', name: 'Solomon Islands', slug: 'solomon-islands', region: 'Oceania' },
  { code: 'SO', name: 'Somalia', slug: 'somalia', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', slug: 'south-africa', region: 'Africa' },
  { code: 'SS', name: 'South Sudan', slug: 'south-sudan', region: 'Africa' },
  { code: 'ES', name: 'Spain', slug: 'spain', region: 'Europe' },
  { code: 'LK', name: 'Sri Lanka', slug: 'sri-lanka', region: 'Asia' },
  { code: 'SD', name: 'Sudan', slug: 'sudan', region: 'Africa' },
  { code: 'SR', name: 'Suriname', slug: 'suriname', region: 'South America' },
  { code: 'SE', name: 'Sweden', slug: 'sweden', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', slug: 'switzerland', region: 'Europe' },
  { code: 'TW', name: 'Taiwan', slug: 'taiwan', region: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', slug: 'tajikistan', region: 'Asia' },
  { code: 'TZ', name: 'Tanzania', slug: 'tanzania', region: 'Africa' },
  { code: 'TH', name: 'Thailand', slug: 'thailand', region: 'Asia' },
  { code: 'TL', name: 'Timor-Leste', slug: 'timor-leste', region: 'Asia' },
  { code: 'TG', name: 'Togo', slug: 'togo', region: 'Africa' },
  { code: 'TO', name: 'Tonga', slug: 'tonga', region: 'Oceania' },
  { code: 'TT', name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago', region: 'Caribbean' },
  { code: 'TN', name: 'Tunisia', slug: 'tunisia', region: 'Africa' },
  { code: 'TR', name: 'Turkey', slug: 'turkey', region: 'Middle East' },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    slug: 'turks-and-caicos-islands',
    region: 'Caribbean',
  },
  { code: 'UG', name: 'Uganda', slug: 'uganda', region: 'Africa' },
  { code: 'UA', name: 'Ukraine', slug: 'ukraine', region: 'Europe' },
  { code: 'AE', name: 'United Arab Emirates', slug: 'united-arab-emirates', region: 'Middle East' },
  { code: 'GB', name: 'United Kingdom', slug: 'united-kingdom', region: 'Europe' },
  { code: 'US', name: 'United States', slug: 'united-states', region: 'North America' },
  { code: 'UY', name: 'Uruguay', slug: 'uruguay', region: 'South America' },
  { code: 'UZ', name: 'Uzbekistan', slug: 'uzbekistan', region: 'Asia' },
  { code: 'VU', name: 'Vanuatu', slug: 'vanuatu', region: 'Oceania' },
  { code: 'VA', name: 'Vatican City', slug: 'vatican-city', region: 'Europe' },
  { code: 'VE', name: 'Venezuela', slug: 'venezuela', region: 'South America' },
  { code: 'VN', name: 'Vietnam', slug: 'vietnam', region: 'Asia' },
  { code: 'YE', name: 'Yemen', slug: 'yemen', region: 'Middle East' },
  { code: 'ZM', name: 'Zambia', slug: 'zambia', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', slug: 'zimbabwe', region: 'Africa' },
  { code: 'FO', name: 'Faroe Islands', slug: 'faroe-islands', region: 'Europe' },
  { code: 'BQ', name: 'Bonaire', slug: 'bonaire', region: 'Caribbean' },
];

const byCode = new Map<string, CountryInfo>();
for (const c of COUNTRIES) {
  byCode.set(c.code, c);
}

/** FiRoam display names → ISO code. Only single-country names; regional bundles are excluded. */
const FIROAM_NAME_TO_CODE: Record<string, string> = {
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Anguilla: 'AI',
  'Antigua & Barbuda': 'AG',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Bolivia: 'BO',
  'Bosnia &  Herzegovina': 'BA',
  Brazil: 'BR',
  Brunei: 'BN',
  Bulgaria: 'BG',
  Cambodia: 'KH',
  Canada: 'CA',
  'Cayman Islands': 'KY',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  'China.HongKong': 'HK',
  'China.Macau': 'MO',
  'China.Taiwan': 'TW',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  DRC: 'CD',
  Denmark: 'DK',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  Estonia: 'EE',
  'Faroe Islands': 'FO',
  Fiji: 'FJ',
  Finland: 'FI',
  France: 'FR',
  'French Guiana': 'GF',
  Gabon: 'GA',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Grenada: 'GD',
  Guatemala: 'GT',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Korea: 'KR',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Latvia: 'LV',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Macedonia: 'MK',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Malta: 'MT',
  Mauritius: 'MU',
  Mexico: 'MX',
  Moldova: 'MD',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Montserrat: 'MS',
  Morocco: 'MA',
  Nepal: 'NP',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Republic of the Congo': 'CG',
  Reunion: 'RE',
  Romania: 'RO',
  Russia: 'RU',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  'St. Kitts & Nevis': 'KN',
  'St. Lucia': 'LC',
  'St. Vincent & the Grenadines': 'VC',
  Sweden: 'SE',
  Switzerland: 'CH',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  Tonga: 'TO',
  Tunisia: 'TN',
  Turkey: 'TR',
  'Turks & Caicos Islands': 'TC',
  UAE: 'AE',
  USA: 'US',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Kingdom': 'GB',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  'Vatican City': 'VA',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Zambia: 'ZM',
};

export function getCountryByCode(code: string): CountryInfo | undefined {
  return byCode.get(code.toUpperCase());
}

/** Resolve a FiRoam display name to an ISO code. Returns undefined for regional bundles. */
export function firoamNameToCode(name: string): string | undefined {
  return FIROAM_NAME_TO_CODE[name];
}
