# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d9541e35a5924941f451d33bf1c4c8f"
name = "esim_fulfillment"
application_url = "https://dashboard.sailesim.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhook/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhook/orders/cancelled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_themes,write_themes,write_draft_orders,read_draft_orders,customer_read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
